### ISSUE TITLE
Question: Working with Google Cloud Storage

### ISSUE THREAD

**Issue by jmaguirrei** [joshuatz/gcp-proxy-func#1]
Hello, I am trying to access files (html, js, css) located in **Google Cloud Storage** from my website.

The thing is that the browser does not allow an `<iframe>` to execute code hosted on another domain, for security reasons.

So I thought about accessing this same files, but behind a reverse proxy, so it seems that a cloud function may do the job.
I also use Firebase Hosting, so I can rewrite the desired route to the function.

I am new to Cloud Functions, so my question is: Given that the bucket may be private (they are by default), do you know if this cloud function will still be capable of reaching the resources?

Thanks

**Comment by joshuatz** [comment]
@jmaguirrei Hmm. I can't say I'm super familiar with your type of scenario, but I'll do my best to answer your question, with help from some quick research on my part:

## Can this cloud function reach the resources in private bucket?
As-is? Yes and no. Just because the cloud function might be running in the same Google account / auth umbrella as the bucket, doesn't mean that it automatically *"unlocks"* it.

From some quick research, it looks like the two main ways to fetch assets from a private bucket are:

 - If you are requiring your users / visitors to be signed in with Google: Give their user access to the bucket (or certain assets) with [Access Control](https://cloud.google.com/storage/docs/access-control), and then [pass their auth info](https://cloud.google.com/storage/docs/access-control/cookie-based-authentication) via the standard `header`.
 - If you want to allow anyone to view certain assets (while still having the bucket be private), you can use [temporary signed URLs](https://cloud.google.com/storage/docs/access-control/signed-urls).

Either of those options should technically work with this cloud function; it does not strip auth headers (afaik) and proxying to signed URLs should not be an issue. *However*, **creating** those signed URLs or handling the OAuth flow is *not* part of this function. You would have to do that yourself. Or find an existing solution ([this](https://github.com/daichirata/gcsproxy) might be close to what you are looking for).

## Use with IFrames
Before you go too far down the above route, I would just warn that I'm not sure how proxying the requests will bypass an iframe restriction. If your website is blocking an iframe from loading, that sounds like you [have a CSP in place](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy); if that is the case, the proxy URL would *also* get blocked, unless the CSP has `cloudfunctions.net` in the allowlist.

I could be way off though; I don't know enough about your specific situation to speak with confidence on that.
